workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
      java: 17
      vars:
        CAPACITOR_ANDROID_STUDIO_PATH: ""
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app first
        script: |
          npm run build
      - name: Setup Capacitor Android
        script: |
          # Remove existing android folder if corrupted
          rm -rf android
          # Add Android platform fresh
          npx cap add android
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Set permissions and build APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
