workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Setup Capacitor Android
        script: |
          rm -rf android
          npx cap add android
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
